version: '3.6'

# Networks
networks:
  mfa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

# Platform Services
services:

  # Nginx Load Balancer Proxy 
  nginx:
    container_name: nginx_load_balancer
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mfa_service_1
      - mfa_service_2
    networks:
      mfa_network:
        ipv4_address: 192.168.0.5

  # MFA Service
  mfa_service_1:
    container_name: mfa_service_1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_hotspot
    networks:
      mfa_network:
        ipv4_address: 192.168.0.10

  # MFA Service
  mfa_service_2:
    container_name: mfa_service_2
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_hotspot
    networks:
      mfa_network:
        ipv4_address: 192.168.0.15

  # MFA Service
  mfa_service_3:
    container_name: mfa_service_3
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_hotspot
    networks:
      mfa_network:
        ipv4_address: 192.168.0.20

  # Redis Master Node
  redis-master-node:
    image: 'redis:6.0-alpine'
    command: redis-cli --cluster create 192.168.0.30:6373 192.168.0.35:6373 192.168.0.40:6373 192.168.0.45:6373 192.168.0.50:6373 192.168.0.55:6373 --cluster-replicas 1 --cluster-yes
    networks:
      mfa_network:
        ipv4_address: 192.168.0.25
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6

  # Redis Node 1
  redis-node-1:
      image: 'redis:6.0-alpine'
      container_name: redis-node-1
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '6373:6373'
      volumes:
        - ./redis/data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        mfa_network:
          ipv4_address: 192.168.0.30

  # Redis Node 2
  redis-node-2:
      image: 'redis:6.0-alpine'
      container_name: redis-node-2
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        mfa_network:
          ipv4_address: 192.168.0.35

  # Redis Node 3
  redis-node-3:
      image: 'redis:6.0-alpine'
      container_name: redis-node-3
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        mfa_network:
          ipv4_address: 192.168.0.40

  # Redis Node 4
  redis-node-4:
      image: 'redis:6.0-alpine'
      container_name: redis-node-4
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        mfa_network:
          ipv4_address: 192.168.0.45

  # Redis Node 5
  redis-node-5:
      image: 'redis:6.0-alpine'
      container_name: redis-node-5
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        mfa_network:
          ipv4_address: 192.168.0.50

  # Redis Node 6
  redis-node-6:
      image: 'redis:6.0-alpine'
      container_name: redis-node-6
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/data:/var/lib/redis
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        mfa_network:
          ipv4_address: 192.168.0.55

  # P3X Redis UI is a very functional handy database GUI and works in your pocket on the responsive web or as a desktop app
  redis-ui:
    image: patrikx3/p3x-redis-ui
    container_name: redis-ui
    ports:
      - 7843:7843
    volumes: 
      - ./redis/ui:/settings
    networks:
        mfa_network:
          ipv4_address: 192.168.0.60