
mfa:
  senders:
    - {
      type: "SMS",
      name: "SMS OTP Sender",
      messageTitle: "Test",
      messageTemplate: "Confirmation code: ${otp}",
      otpLength: 5,
      useLetters: false,
      useDigits: true,
      ttlMinutes: 3
    }

redis:
  nodes:
    - { host: 192.168.0.30, port: 6373 }
    - { host: 192.168.0.35, port: 6373 }
    - { host: 192.168.0.40, port: 6373 }
    - { host: 192.168.0.45, port: 6373 }
    - { host: 192.168.0.50, port: 6373 }
    - { host: 192.168.0.55, port: 6373 }
