version: '3.6'


# Platform Services
services:

  # Nginx Load Balancer Proxy 
  nginx:
    container_name: nginx_load_balancer
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mfa_service_1
      - mfa_service_2
      - mfa_service_3

  # MFA Service
  mfa_service_1:
    container_name: mfa_service_1
    image: 'ssanchez11/mfa_service:0.0.1'
    restart: always

  # MFA Service
  mfa_service_2:
    container_name: mfa_service_2
    image: 'ssanchez11/mfa_service:0.0.1'
    restart: always

  # MFA Service
  mfa_service_3:
    container_name: mfa_service_3
    image: 'ssanchez11/mfa_service:0.0.1'
    restart: always