version: '3.6'


# Platform Services
services:

  # HAProxy Load Balancer Proxy 
  haproxy:
    image: haproxytech/haproxy-alpine:2.7
    container_name: haproxy
    volumes:
        - ./haproxy:/usr/local/etc/haproxy:ro
    links:
        - mfa_service_1
        - mfa_service_2
        - mfa_service_3
        - mfa_service_4
    ports:
        - "9090:9090"
        - "8404:8404"

  # FTP configuration repository
  ftp_repository:
    container_name: ftp_repository
    image: garethflowers/ftp-server
    environment:
      - FTP_PASS=thunderotp00
      - FTP_USER=thunderotp
    volumes:
      - './ftp/data:/home/thunderotp'

  # MFA Service
  mfa_service_1:
    container_name: mfa_service_1
    image: 'ssanchez11/mfa_service_hotspot:0.0.1'
    links:
        - ftp_repository

  # MFA Service
  mfa_service_2:
    container_name: mfa_service_2
    image: 'ssanchez11/mfa_service_hotspot:0.0.1'
    links:
        - ftp_repository

  # MFA Service
  mfa_service_3:
    container_name: mfa_service_3
    image: 'ssanchez11/mfa_service_hotspot:0.0.1'
    links:
        - ftp_repository

   # MFA Service
  mfa_service_4:
    container_name: mfa_service_4
    image: 'ssanchez11/mfa_service_hotspot:0.0.1'
    links:
        - ftp_repository