version: '3.6'

# Networks
networks:
  mfa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

# Platform Services
services:

  # Nginx Load Balancer Proxy 
  nginx:
    container_name: nginx_load_balancer
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mfa_service_1
      - mfa_service_2
    networks:
      mfa_network:
        ipv4_address: 192.168.0.5

  # MFA Service
  mfa_service_1:
    container_name: mfa_service_1
    restart: always
    build:
      context: ./microservice
      dockerfile: Dockerfile_hotspot
    networks:
      mfa_network:
        ipv4_address: 192.168.0.10

  # MFA Service
  mfa_service_2:
    container_name: mfa_service_2
    restart: always
    build:
      context: ./microservice
      dockerfile: Dockerfile_hotspot
    networks:
      mfa_network:
        ipv4_address: 192.168.0.15

  # MFA Service
  mfa_service_3:
    container_name: mfa_service_3
    restart: always
    build:
      context: ./microservice
      dockerfile: Dockerfile_hotspot
    networks:
      mfa_network:
        ipv4_address: 192.168.0.20