
mfa:
  senders:
    smsSender: {
      messageTitle: "Test",
      messageTemplate: "Your OTP is: #otp, and it's valid for 5 minutes.",
      otpLength: 5,
      useLetters: false,
      useDigits: true,
      ttlMinutes: 5,
      accountSid: "secret",
      serviceKey: "secret",
      fromPhoneNumber: "secret"
    }
    pushSender: {
      messageTitle: "Test",
      messageTemplate: "Confirmation code: #otp",
      otpLength: 10,
      useLetters: true,
      useDigits: true,
      ttlMinutes: 3,
      serviceKey: "secret",
      serviceUrl: "https://fcm.googleapis.com/fcm/send"
    }
    mailSender: {
      messageTitle: "Test",
      messageTemplate: "Confirmation code: #otp",
      otpLength: 20,
      useLetters: true,
      useDigits: true,
      ttlMinutes: 10,
      serviceKey: "secret",
      emailFrom: "secret",
      emailFromName: "secret",
      messageTemplateId: "d-eb46147a705f442b973e809f0205337c",
      messageTitlePlaceholder: "message_title",
      messageContentPlaceholder: "message_content"
    }


redis:
  nodes:
    - { host: 192.168.0.30, port: 6373 }
    - { host: 192.168.0.35, port: 6373 }
    - { host: 192.168.0.40, port: 6373 }
    - { host: 192.168.0.45, port: 6373 }
    - { host: 192.168.0.50, port: 6373 }
    - { host: 192.168.0.55, port: 6373 }
