FROM openjdk:11-jdk-slim
RUN apt-get update
RUN apt-get install -y dos2unix

WORKDIR /src
COPY . /src
RUN dos2unix gradlew
RUN bash gradlew buildFatJar --no-daemon --debug
RUN mkdir -p /opt/mfa
RUN cp build/libs/mfa_server.jar /opt/mfa/

WORKDIR /opt/mfa
EXPOSE 8080
CMD java -jar ./mfa_server.jar